version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: react-redis
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    container_name: react-backend
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    container_name: react-frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
